### ISSUE TITLE
cannot find output file in react

### ISSUE THREAD

**Issue by jawn-ha** [react-microfrontends/planets#12]
Hi, I follow the ReadMe but the browser can't find  `https://localhost:9001/react-mf-planets.js`.
I tried use  `create-single-spa` cli to create a react app from scratch but can not find output file too. 
I am confused today for a long time
![image](https://user-images.githubusercontent.com/16000122/85926249-ae961080-b8d0-11ea-8da4-46ef49a06577.png)

**Comment by joeldenning** [comment]
Hi @jawn-ha, good quesstion. When you run `npm start` or `yarn start`, it starts up [webpack-dev-server](), which runs webpack and stores the output bundle in memory. Then webpack-dev-server will handle requests for the file by serving from memory instead of from disk. This is why the file will not appear on disk.

When deploying the code, you should run `yarn build`, which will create a file on disk.

I am closing this since there's no bug in this project and I believe to have answered the question. Feel free to comment further or reopen.
