### ISSUE TITLE
Recommended setup for Typescript

### ISSUE THREAD

**Issue by luthv** [react-microfrontends/planets#16]
I'm playing around with single-spa and typescript projects created with create-single-spa CLI, one thing that I don't get right now is how can we import the utility type module in an application type project and have the typescript compiler not to complain with with ts(2307) cannot find module error?

for example if I have this component in the application that reference the api utility
```ts
import { api } from '@react-mf/api';
```
typescript compiler will said I don't have the react-mf/api module referenced, how can we make this work for local development?

**Comment by joeldenning** [comment]
Hi @luthv, good question. This has been discussed a few times in the single-spa slack workspace.

[Slack invitation link](https://join.slack.com/t/single-spa/shared_invite/enQtODAwNTIyMzc4OTE1LWUxMTUwY2M1MTY0ZGMzOTUzMGNkMzI1NzRiYzYwOWM1MTEzZDM1NDAyNWM3ZmViOTAzZThkMDcwMWZmNTFmMWQ)

[Conversation 1](https://single-spa.slack.com/archives/C8R6U7MT7/p1600121382098400)

[Conversation 2](https://single-spa.slack.com/archives/C8R6U7MT7/p1596014699052600)

Also here's a github thread that discusses it: https://github.com/single-spa/single-spa/issues/609

The summary is that you can either use symlinking, mocking, or publishing the types to npm.

I'm closing this issue since it's been discussed elsewhere, but feel free to comment further or reopen.

**Comment by luthv** [comment]
thanks, I'm going with publishing the type definitions to my github package repo coupled with lerna packages in the utility module so I can keep them in the same repo, it's working so far.
